### ISSUE TITLE
Bổ sung thêm plugin metalsmith-metadata để lấy file json sử dụng chung.

### ISSUE THREAD

**Issue by gattadesmond** [easywebhub/easyweb-metalsmith#10]
Plugin metalsmith : https://github.com/segmentio/metalsmith-metadata lấy data file json sử dụng global. Rất tiện làm dữ liệu giả.

@nemesisqp cài thêm dùm em nhé, thanks a

**Comment by baotnq** [comment]
@gattadesmond cái này anh đã bổ sung rồi, sử dụng plugin khác.
Em chỉ cần bỏ file .json vào thư muc `/content/metadata/` sau đó truy cập theo cấu truc
 `{{ten-file-json.variable}}` là xong.

**Comment by baotnq** [comment]
tham khảo 

https://github.com/easywebhub/easyweb-metalsmith/blob/master/content/metadata/menu.json

@nemesisqp  ko cần chỗ trợ @gattadesmond  vấn đề này nghe.

**Comment by gattadesmond** [comment]
ok, thanks a
