### ISSUE TITLE
Định nghĩa cấu trúc json cho menu

### ISSUE THREAD

**Issue by baotnq** [easywebhub/easyweb-metalsmith#13]
Định nghĩa cấu trúc menu cho các trường hợp
1. Menu 1 cấp
2. Menu 2  cấp
3. Menu nhiều cấp
4. Menu chính bên trên và menu phụ bên trái

**Comment by baotnq** [comment]
@tungptvn @vvthinh  có ý kiến, giải pháp gì ko

**Comment by tungptvn** [comment]
menu nhiều cấp định nghĩa như này được ko a

``` json
[
  {
    "Id": "menu1",
    "title": "tin tuc",
    "link": "tin-tuc",
    "child": null
  },
  {
    "Id": "menu2",
    "title": "tin tuc",
    "link": "tin-tuc",
    "child": [{
        "Id": "menu2_1",
        "title": "tin tuc",
        "link": "tin-tuc",
        "child": null
      },{
        "Id": "menu2_2",
        "title": "tin tuc",
        "link": "tin-tuc",
        "child": null
      }]
  },
  {
    "Id": "menu_3",
    "title": "tin tuc",
    "link": "tin-tuc",
    "child": [
      {
        "Id": "menu3_1",
        "title": "tin tuc",
        "link": "tin-tuc",
        "child": null
      }
    ]
  },
  {
    "Id": "menu4",
    "title": "tin tuc",
    "link": "tin-tuc",
    "child": null
  }
]
```

**Comment by baotnq** [comment]
Đánh giá;  giải pháp là ổn,   good job!
Cần cải thiện như sau:
- "child" : null  có cần định nghĩa ko, có kiểm tra được child != null hay [] ko
-  viết thêm cách hiển thị menu nhiều cấp sử dụng lệnh handlebar
- tạo ra 1 file gist để sử dụng sau này, như file này    [gist](https://gist.github.com/baotnq/38a923c9f22b4c9c1a9a1fc96d18b476)

**Comment by baotnq** [comment]
cách nhúng vào view
<script src="https://gist.github.com/baotnq/38a923c9f22b4c9c1a9a1fc96d18b476.js"></script>

**Comment by tungptvn** [comment]
![image](https://cloud.githubusercontent.com/assets/11553588/16579005/c5734a58-42c7-11e6-9d24-f53899f4a8f4.png)

Viết thêm nav handlebar helper (input metadata nav,json => out code html như hình trên, font-end tự css lại )
