### ISSUE TITLE
Plugin Browsersync không chạy.

### ISSUE THREAD

**Issue by gattadesmond** [easywebhub/easyweb-metalsmith#17]
@nemesisqp a xem giúp em version mới em watch thì plugin Browsersync không chạy, nên khi em sửa css, html thì trình duyệt không load lại. Thanks a. Dưới là hình khi nó có chạy trên bản cũ.

![browsersync1](https://cloud.githubusercontent.com/assets/7348913/16977819/ac1c6294-4e82-11e6-87d6-9a042146cc32.PNG)

**Comment by nemesisqp** [comment]
done tracing, thiếu open body -> browsersync khùng
