### ISSUE TITLE
Metalsmith permalinks not work

### ISSUE THREAD

**Issue by baotnq** [easywebhub/easyweb-metalsmith#5]
Test thử với config

  'metalsmith-permalinks':    {
        '_enable':  true,
        'pattern':  ':title',
        'relative': false
    }

thì thấy file *.html vẫn ko sử dụng title như mong muốn.

@nemesisqp  review xem vấn đề nào dùm anh, và nếu được chuyển plugin này sang dùng easyweb repo tương tự collections.

Hiện tại link sinh ra sẽ có dạng   /blog/xxx.html, hoặc /baiviet/xxx.html, sẽ ko được tối ưu cho SEO.
Tìm cách nào cho các Url đều có dạng   /xxx.html   (bỏ qua việc /blog hoặc /baiviet)

**Comment by nemesisqp** [comment]
rồi đó anh #6
